name: nf-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: latest-stable

      - name: Install nf-test
        run: |
          curl -fsSL https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: nf-test test 